### ISSUE TITLE
Issue with accented characters

### ISSUE THREAD

**Issue by apetitjean** [nightroman/Ldbc#2] opened 2021-03-15 06:50 UTC
Hi,

I cannot store correctly strings containing accented characters like "ùéà".

Is there any option to store strings using a Unicode encoding?

Thanks

**Comment by nightroman** [comment] 2021-03-15 10:17
I cannot reproduce. Example:

```powershell
Import-Module Ldbc

Use-LiteDatabase z.litedb {
    # get the collection, specify auto id
    $test = Get-LiteCollection Test Int32

    # add two documents
    @{Name = 'ùéà'}, @{Name = 'Mary'} | Add-LiteData $test
}

Use-LiteDatabase z.litedb {
    # get the collection, specify auto id
    $test = Get-LiteCollection Test Int32

    # get all documents
    $r = Get-LiteData $test
    "$r"
}
```

Output

```
{"_id":1,"Name":"ùéà"} {"_id":2,"Name":"Mary"}
```

> I cannot store correctly strings containing accented characters like "ùéà".

How exactly do you come to this conclusion?

- How do you store?
- How do you check the result?

**Comment by apetitjean** [comment] 2021-03-15 10:38
Thanks Roman for your response.

I cannot try right now but I'll go back to you very soon.

But since then I'm happy to know that the problem is probably on my side
and LiteDB handles these characters in an appropriate way :-).

Arnaud

Le lun. 15 mars 2021 à 11:18, Roman Kuzmin ***@***.***> a
écrit :

**Comment by nightroman** [comment] 2021-03-15 10:44
@apetitjean No problem, take your time.

**Comment by nightroman** [comment] 2021-03-18 12:01
I'm closing. Feel free to reopen with new input.

**Closed as completed by nightroman** 2021-03-18 12:01 UTC
